### ISSUE TITLE
tab太多会使最后一个tab被刷新和编辑按钮挡住

### ISSUE THREAD

**Issue by yawn0305** [any-block/obsidian-any-block#118]
ob版本：1.7.7
插件版本：3.1.8
如图
![QQ20241231-015059](https://github.com/user-attachments/assets/bbcdb4f6-48e9-4b5e-98ce-8f188757e471)

**Comment by LincZero** [comment]
好了，加了个css：

```css
.ab-tab-nav {
  padding-right: 60px;
}
```
