### ISSUE TITLE
导图希望可以有左右滚动条

### ISSUE THREAD

**Issue by jiajiala** [any-block/obsidian-any-block#87]
![image](https://github.com/user-attachments/assets/0002f1b6-973a-4aec-a4a3-b9589539fcf2)
这种字多的导图，可以不压缩文字，而是在底部拥有一个滑动条可以左右拉进行查看吗

**Comment by LincZero** [comment]
通过自定义css解决：

```css
.ab-nodes-content {
  white-space: nowrap;
  max-width: 300px;
  overflow-x: auto;
}

/* 可选 */
.ab-nodes {
  overflow-x: auto;
}
```
