### ISSUE TITLE
编辑的时候 底部的绿色线条 如何去掉

### ISSUE THREAD

**Issue by jiajiala** [any-block/obsidian-any-block#91]
![image](https://github.com/user-attachments/assets/388491a5-7093-4fde-9618-6bde58f25022)
我不想在编辑的时候有一个绿色线条在底下
美债到css去除的办法，求教

**Comment by LincZero** [comment]
自定义样式

```css
.ab-line-yellow {
  text-decoration: none !important
}
```
